version: '4'

services:
  app:
    build: .
    container_name: todo-api
    command: sh -c "gunicorn -w 4 -b 0.0.0.0:8080 wsgi:app"
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - .:/todo-api
